# Workflow name
name: Build and deploy ASP.Net Core app to Azure Web App - digitalGarden

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET 9 Preview
              run: |
                  wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
                  chmod +x dotnet-install.sh
                  ./dotnet-install.sh --version 9.0.0-preview.3.24167.7 --install-dir $HOME/.dotnet
                  echo "$HOME/.dotnet" >> $GITHUB_PATH
                  echo "DOTNET_ROOT=$HOME/.dotnet" >> $GITHUB_ENV

            - name: Build with dotnet
              run: dotnet build --configuration Release

            - name: dotnet publish
              run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: .net-app
                  path: ${{env.DOTNET_ROOT}}/myapp

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: .net-app

            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "digitalGarden"
                  slot-name: "Production"
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: .
